import './globals.css'
import { CssBaseline, ThemeProvider } from '@mui/material';
import { baselightTheme } from "./theme/DefaultColors";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const theme = baselightTheme;
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>

        <CssBaseline />
      <body>{children}</body>
      </ThemeProvider>
    </html>
  )
}
